# Generated by Django 5.2.9 on 2025-12-17 08:29

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0002_recipe"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="recipe",
            options={"ordering": ["-pk"]},
        ),
        migrations.AddField(
            model_name="recipe",
            name="link",
            field=models.URLField(blank=True, null=True, verbose_name="link"),
        ),
        migrations.AlterField(
            model_name="recipe",
            name="duration_minute",
            field=models.PositiveSmallIntegerField(
                validators=[django.core.validators.MinValueValidator(0.01)],
                verbose_name="duration minute",
            ),
        ),
        migrations.AlterField(
            model_name="recipe",
            name="price",
            field=models.DecimalField(
                decimal_places=2,
                max_digits=5,
                validators=[django.core.validators.MinValueValidator(0)],
                verbose_name="price",
            ),
        ),
    ]
