# Generated by Django 5.2.9 on 2025-12-18 16:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0007_ingredient"),
    ]

    operations = [
        migrations.AddField(
            model_name="recipe",
            name="ingredients",
            field=models.ManyToManyField(
                to="core.ingredient", verbose_name="ingredients"
            ),
        ),
    ]
