# Generated by Django 5.2.9 on 2025-12-20 15:37

import core.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0008_recipe_ingredients"),
    ]

    operations = [
        migrations.AddField(
            model_name="recipe",
            name="image",
            field=models.ImageField(
                null=True,
                upload_to=core.models.generate_image_recipe_path,
                verbose_name="image",
            ),
        ),
    ]
